config-linux-common.h: fix glibc build failure
Recent glibc v2.30 dropped XSI STREAMS declarations,
which causing below build failure.

poky/build/tmp/work/corei7-64-poky-linux/ace/6.5.6-r0/ACE_wrappers/ace/os_include/os_stropts.h:56:17: fatal error: stropts.h: No such file or directory
   56 | #  include /**/ <stropts.h>
      |                 ^~~~~~~~~~~
compilation terminated.

Added _XOPEN_STREAMS not defined checks for newer GLIBC releases.

For more information about glibc v2.30 change, please check:
https://sourceware.org/git/?p=glibc.git;a=commit;h=a0a0dc83173ce11ff45105fd32e5d14356cdfb9c

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>